{
 "title": "Barista Kafka",
 "description": "Visualize Quarkus MicroProfile Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "base_cpu_systemLoadAverage{job=\"barista-kafka\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Daemon Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_thread_daemon_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Live Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_thread_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Peak Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_thread_max_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available Processors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Used Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{instance=~\"$instance\"}",
     "legendFormat": "Committed Heap"
    }
   ]
  }
 ]
}